version: "3.4"

services:
    localstack:
        container_name: sf_localstack
        image: localstack/localstack:latest
        environment:
            - AWS_DEFAULT_REGION=us-west-2
            - HOSTNAME_EXTERNAL=localhost
            - SERVICES=sqs
            - DEBUG=0
            # - DATA_DIR=/tmp/localstack/data
        ports:
            - 4566:4566 # Edge

    step-functions:
        container_name: step-functions
        image: amazon/aws-stepfunctions-local
        depends_on:
            - localstack
        environment:
            - AWS_DEFAULT_REGION=us-west-2
            - AWS_ACCESS_KEY_ID=12345
            - AWS_SECRET_ACCESS_KEY=12345
            - SQS_ENDPOINT=host.docker.internal:4566
        ports:
            - 8083:8083
